INSERT INTO Reviews (user_id, item_id, review_text)
VALUES (1, 1, 'Great food and friendly service! Highly recommend the burgers.'),
       (2, 1, 'Loved the vibe, but the fries were a bit soggy.'),
       (1, 2, 'The pasta was delicious and the atmosphere was cozy.'),
       (2, 2, 'Too much cream in the Alfredo, but the lasagna was fantastic.'),
       (3, 3, 'Best sushi Ive ever had! Fresh and flavorful.'),
       (4, 3, 'A great place for a date night, loved the ambiance.'),
       (1, 4, 'Absolutely loved the vegan burger, one of the best Ive tried.'),
       (3, 4, 'Good options, but some dishes were bland.'),
       (2, 5, 'Pizza was amazing, and the service was quick.'),
       (1, 5, 'The crust was perfect!'),
       (2, 6, 'A cinematic masterpiece! The story is captivating.'),
       (3, 6, 'Classic film, loved every moment of it.'),
       (4, 7, 'Mind-blowing! The concept is brilliantly executed.'),
       (5, 7, 'Great visual effects and a thought-provoking plot.'),
       (2, 8, 'An epic space adventure with emotional depth.'),
       (1, 8, 'Absolutely loved the ending. Highly recommend.'),
       (3, 9, 'A tragic love story that still resonates today.'),
       (2, 10, 'Groundbreaking in every sense. A must-watch.'),
       (1, 11, 'A chilling portrayal of a dystopian future.'),
       (4, 11, 'Thought-provoking and well-written.'),
       (2, 12, 'A powerful story about courage and empathy.'),
       (1, 12, 'Timeless classic, a must-read for everyone.'),
       (2, 13, 'An engaging read, kept me on my toes!'),
       (3, 14, 'A beautiful story about dreams and ambitions.'),
       (1, 15, 'Fantastic insight into human history and evolution.'),
       (3, 16, 'An enlightening read that challenges conventional thought.'),
       (5, 17, 'Great rhythm and storytelling in every song.'),
       (2, 18, 'A wonderful collection of songs that uplift the spirit.'),
       (4, 19, 'A classic that never gets old. Truly inspiring.'),
       (3, 20, 'A fantastic album with a blend of styles.');