INSERT INTO Images (user_id, item_id, image_url)
VALUES (1, 1, 'https://example.com/images/joes_diner.jpg'),
       (2, 1, 'https://example.com/images/joes_diner_2.jpg'),
       (1, 2, 'https://example.com/images/pasta_palace.jpg'),
       (2, 2, 'https://example.com/images/pasta_palace_2.jpg'),
       (3, 3, 'https://example.com/images/sushi_haven.jpg'),
       (4, 3, 'https://example.com/images/sushi_haven_2.jpg'),
       (1, 4, 'https://example.com/images/vegan_delight.jpg'),
       (2, 4, 'https://example.com/images/vegan_delight_2.jpg'),
       (3, 5, 'https://example.com/images/pizza_place.jpg'),
       (4, 5, 'https://example.com/images/pizza_place_2.jpg'),
       (1, 6, 'https://example.com/images/the_godfather.jpg'),
       (2, 6, 'https://example.com/images/the_godfather_2.jpg'),
       (1, 7, 'https://example.com/images/inception.jpg'),
       (2, 7, 'https://example.com/images/inception_2.jpg'),
       (1, 8, 'https://example.com/images/interstellar.jpg'),
       (2, 8, 'https://example.com/images/interstellar_2.jpg'),
       (1, 9, 'https://example.com/images/titanic.jpg'),
       (2, 9, 'https://example.com/images/titanic_2.jpg'),
       (1, 10, 'https://example.com/images/the_matrix.jpg'),
       (2, 10, 'https://example.com/images/the_matrix_2.jpg');