INSERT INTO Users (username, email, password, first_name, last_name, date_of_birth, profile_image, bio)
VALUES ('john_doe', 'john@example.com', 'password123', 'John', 'Doe', '1985-06-15',
        'https://example.com/images/john.jpg', 'Food enthusiast and traveler.'),
       ('jane_smith', 'jane@example.com', 'securepass456', 'Jane', 'Smith', '1990-03-22',
        'https://example.com/images/jane.jpg', 'Lover of coffee and books.'),
       ('mike_jones', 'mike@example.com', 'mypassword789', 'Mike', 'Jones', '1992-07-10',
        'https://example.com/images/mike.jpg', 'Tech geek and gamer.'),
       ('sara_connor', 'sara@example.com', 'pass1234', 'Sara', 'Connor', '1988-11-30',
        'https://example.com/images/sara.jpg', 'Fitness and wellness advocate.'),
       ('linda_brown', 'linda@example.com', 'lindapass567', 'Linda', 'Brown', '1987-02-14',
        'https://example.com/images/linda.jpg', 'Avid traveler and food blogger.'),
       ('tom_clark', 'tom@example.com', 'tompassword234', 'Tom', 'Clark', '1983-05-25',
        'https://example.com/images/tom.jpg', 'History buff and nature lover.'),
       ('alice_williams', 'alice@example.com', 'alicepass345', 'Alice', 'Williams', '1995-09-19',
        'https://example.com/images/alice.jpg', 'Art lover and creative writer.'),
       ('bob_johnson', 'bob@example.com', 'bobpass456', 'Bob', 'Johnson', '1991-03-03',
        'https://example.com/images/bob.jpg', 'Hiking enthusiast and coffee lover.'),
       ('charlie_davis', 'charlie@example.com', 'charliepass678', 'Charlie', 'Davis', '1986-12-12',
        'https://example.com/images/charlie.jpg', 'Film critic and foodie.'),
       ('daisy_thompson', 'daisy@example.com', 'daisypass789', 'Daisy', 'Thompson', '1994-04-04',
        'https://example.com/images/daisy.jpg', 'Gadget geek and bookworm.'),
       ('ethan_anderson', 'ethan@example.com', 'ethanpass890', 'Ethan', 'Anderson', '1989-08-08',
        'https://example.com/images/ethan.jpg', 'Music lover and sports fan.'),
       ('grace_martinez', 'grace@example.com', 'gracepass901', 'Grace', 'Martinez', '1993-01-01',
        'https://example.com/images/grace.jpg', 'Yoga instructor and wellness blogger.'),
       ('henry_moore', 'henry@example.com', 'henrypass012', 'Henry', 'Moore', '1980-06-30',
        'https://example.com/images/henry.jpg', 'Philosophy enthusiast and musician.'),
       ('isabella_taylor', 'isabella@example.com', 'isabellapass123', 'Isabella', 'Taylor', '1992-02-15',
        'https://example.com/images/isabella.jpg', 'Fashionista and travel junkie.'),
       ('jackson_hall', 'jackson@example.com', 'jacksonpass234', 'Jackson', 'Hall', '1995-10-20',
        'https://example.com/images/jackson.jpg', 'Adventure seeker and sports enthusiast.');