INSERT INTO Items (item_name, description, category_id)
VALUES ('Joes Diner', 'A cozy diner serving classic American comfort food.', 1),
       ('Pasta Palace', 'An Italian restaurant known for its homemade pasta.', 1),
       ('Sushi Haven', 'Fresh sushi and Japanese cuisine.', 1),
       ('Vegan Delight', 'Healthy and delicious plant-based meals.', 1),
       ('Pizza Place', 'Best pizza in town with a variety of toppings.', 1),
       ('The Godfather', 'A classic crime film directed by Francis Ford Coppola.', 2),
       ('Inception', 'A mind-bending thriller about dream invasion.', 2),
       ('Interstellar', 'A sci-fi epic exploring space travel and time.', 2),
       ('Titanic', 'A romantic disaster film based on real events.', 2),
       ('The Matrix', 'A groundbreaking sci-fi film about reality.', 2),
       ('1984', 'A dystopian novel by George Orwell.', 3),
       ('To Kill a Mockingbird', 'A novel about racial injustice in the Deep South.', 3),
       ('The Catcher in the Rye', 'A story about teenage alienation and loss.', 3),
       ('The Great Gatsby', 'A classic novel about the American dream.', 3),
       ('Sapiens: A Brief History of Humankind', 'A thought-provoking book on human evolution.', 3),
       ('The Weeknd - Starboy', 'An album featuring hit songs by The Weeknd.', 4),
       ('Coldplay - A Head Full of Dreams', 'A popular album by the British rock band.', 4),
       ('Beethoven Symphony No. 9', 'A classical masterpiece.', 4),
       ('Taylor Swift - Folklore', 'An album showcasing Taylor Swifts storytelling.', 4),
       ('Chess', 'A strategy board game played worldwide.', 5),
       ('Minecraft', 'A sandbox video game about creativity and exploration.', 5),
       ('Call of Duty', 'A popular first-person shooter video game series.', 5),
       ('The Legend of Zelda', 'An action-adventure video game series.', 5),
       ('The Hobbit', 'A fantasy novel by J.R.R. Tolkien.', 3),
       ('The Alchemist', 'A novel about following ones dreams.', 3),
       ('Brave New World', 'A dystopian novel by Aldous Huxley.', 3),
       ('Fahrenheit 451', 'A novel about censorship and the future.', 3);