INSERT INTO Categories (category_name)
VALUES ('Restaurant'),
       ('Movie'),
       ('Book'),
       ('Music'),
       ('Game'),
       ('Travel'),
       ('Fitness'),
       ('Technology'),
       ('Art'),
       ('Fashion'),
       ('Sport'),
       ('History'),
       ('Science'),
       ('Food'),
       ('Nature'),
       ('Photography');