openapi: 3.0.0
info:
  title: Rate This Thing API
  version: 1.0.0
  description: API documentation for the "Rate This Thing" application.

paths:
  /users:
    get:
      summary: Retrieve a list of users
      operationId: getUsers
      tags:
        - User # Tag to identify this operation
      responses:
        '200':
          description: A list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserDTO' # Reference the User schema

components:
  schemas:
    UserDTO:
      type: object
      properties:
        id:
          type: integer
          example: 1
        username:
          type: string
          example: johndoe
        email:
          type: string
          example: johndoe@example.com
        firstName:
          type: string
          example: John
        lastName:
          type: string
          example: Doe
        dateOfBirth:
          type: string
          format: date
          example: 1990-01-01
        profileImage:
          type: string
          example: http://example.com/profile.jpg
        bio:
          type: string
          example: This is a user bio.
