openapi: 3.0.0
info:
  title: Sample API
  version: 1.0.0
  description: A simple API to retrieve items.

servers:
  - url: http://api.example.com/v1

paths:
  /items:
    get:
      summary: Retrieve a list of items
      operationId: getItems
      responses:
        '200':
          description: A list of items
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    name:
                      type: string
                      example: Item Name
                    description:
                      type: string
                      example: This is an item description.

components:
  schemas:
    Item:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        description:
          type: string
